In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("C:\Price Forecasting Datens√§tze\Sheet1.xlsm")

In [3]:
df

,TIME,1996-01,Unnamed: 2,1996-02,Unnamed: 4,1996-03,Unnamed: 6,1996-04,Unnamed: 8,1996-05,...,Unnamed: 652,2023-03,Unnamed: 654,2023-04,Unnamed: 656,2023-05,Unnamed: 658,2023-06,Unnamed: 660,2023-07
0,Belgium,65.83,NaN,65.96,NaN,66.42,NaN,66.69,NaN,67.15,...,NaN,135.76,NaN,133.49,NaN,134.04,NaN,134.21,NaN,:
1,Bulgaria,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,165.84,NaN,166.06,NaN,166.73,NaN,165.76,NaN,:
2,Czechia,67.7,NaN,68.1,NaN,68.9,NaN,69.6,NaN,70.4,...,NaN,152.8,NaN,150.3,NaN,151.7,NaN,151.7,NaN,:
3,Denmark,68.2,NaN,68.4,NaN,68.7,NaN,68.8,NaN,69.2,...,NaN,128.3,NaN,127.6,NaN,128.3,NaN,129.7,NaN,:
4,Germany,75.7,NaN,76.3,NaN,76.7,NaN,77,NaN,76.8,...,NaN,144.9,NaN,144.2,NaN,144,NaN,144,NaN,:
5,Estonia,48.18,NaN,50.55,NaN,51.51,NaN,52.44,NaN,52.72,...,NaN,161.41,NaN,163.3,NaN,163.17,NaN,165.32,NaN,:
6,Ireland,79,NaN,79.3,NaN,79.7,NaN,80.1,NaN,80.5,...,NaN,107.5,NaN,108.3,NaN,108.7,NaN,108.8,NaN,:
7,Greece,60.18,NaN,60.87,NaN,62.36,NaN,63.24,NaN,64.11,...,NaN,125.02,NaN,124.94,NaN,127.48,NaN,131.67,NaN,:
8,Spain,63.99,NaN,63.87,NaN,63.8,NaN,64.38,NaN,64.83,...,NaN,135.33,NaN,135.69,NaN,136.2,NaN,136.54,NaN,:
9,France,72.8,NaN,72.94,NaN,73.55,NaN,73.5,NaN,74.21,...,NaN,130.76,NaN,131.46,NaN,131.88,NaN,132.21,NaN,:
10,Croatia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,136.58,NaN,137.87,NaN,140.06,NaN,141.95,NaN,:
11,Italy,68.9,NaN,69.1,NaN,69.4,NaN,70,NaN,70.5,...,NaN,126.6,NaN,127.1,NaN,128.4,NaN,128.8,NaN,:
12,Cyprus,51.82,NaN,51.99,NaN,53.63,NaN,52.99,NaN,52.88,...,NaN,119.66,NaN,120.71,NaN,122.81,NaN,121.91,NaN,:
13,Latvia,44.57,NaN,45.62,NaN,46.73,NaN,46.95,NaN,47.04,...,NaN,161.7,NaN,162.38,NaN,162.25,NaN,162.09,NaN,:
14,Lithuania,55.99,NaN,57.95,NaN,59.88,NaN,61.11,NaN,61.31,...,NaN,168.6,NaN,169.84,NaN,169.88,NaN,168.38,NaN,:
15,Luxembourg,64.11,NaN,64.04,NaN,64.17,NaN,64.3,NaN,64.37,...,NaN,131.3,NaN,132.1,NaN,132.52,NaN,132.89,NaN,:
16,Hungary,29.98,d,30.55,d,31.03,d,31.31,d,31.56,...,NaN,201.39,NaN,200.43,NaN,200.18,NaN,198.7,NaN,:
17,Malta,56.83,NaN,57.83,NaN,59.06,NaN,59.63,NaN,59.37,...,NaN,138.48,NaN,138.67,NaN,140.14,NaN,141.5,NaN,:
18,Netherlands,74.79,NaN,75.02,NaN,76.36,NaN,76.21,NaN,75.09,...,NaN,136.89,NaN,136.63,NaN,137.75,NaN,138.15,NaN,:
19,Austria,68.07,NaN,68.2,NaN,68.95,NaN,68.61,NaN,68.34,...,NaN,132.05,NaN,133.11,NaN,133.4,NaN,134.36,NaN,:
20,Poland,47.5,d,48.4,d,49.5,d,50.9,d,51.4,...,NaN,161.5,NaN,162.3,NaN,163.5,NaN,163.1,NaN,:
21,Portugal,72.47,NaN,72.91,NaN,72.99,NaN,74.32,NaN,74.91,...,NaN,134.69,NaN,134.55,NaN,130.4,NaN,130.8,NaN,:
22,Romania,4.39,NaN,4.48,NaN,4.54,NaN,4.66,NaN,4.99,...,NaN,158.95,NaN,160.7,NaN,161.88,NaN,161.44,NaN,:
23,Slovenia,44.02,NaN,45,NaN,46.2,NaN,47.36,NaN,47.55,...,NaN,140.43,NaN,140.31,NaN,141.41,NaN,140.63,NaN,:
24,Slovakia,57,NaN,56.6,NaN,56.55,NaN,56.71,NaN,56.87,...,NaN,159.8,NaN,160.18,NaN,160.82,NaN,160.73,NaN,:
25,Finland,68.19,NaN,68.74,NaN,69.15,NaN,69.22,NaN,69.5,...,NaN,126.26,NaN,124.72,NaN,125.02,NaN,124.46,NaN,:
26,Sweden,72.04,NaN,72.23,NaN,73.33,NaN,73.53,NaN,73.53,...,NaN,142.26,NaN,140.76,NaN,140.13,NaN,140.45,NaN,:
27,Iceland,44.65,NaN,44.79,NaN,45.2,NaN,45.51,NaN,45.7,...,NaN,133.06,NaN,135.05,NaN,136.13,NaN,136.97,NaN,:
28,Norway,68.6,NaN,68.6,NaN,68.8,NaN,69,NaN,69.5,...,NaN,118.3,NaN,121.3,NaN,123.8,NaN,126.7,NaN,:
29,Switzerland,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,106.53,NaN,105.67,NaN,107.45,NaN,108.48,NaN,:
30,United Kingdom,64.9,NaN,65.6,NaN,66.1,NaN,66.1,NaN,66.6,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
31,Montenegro,:,NaN,:,NaN,:,NaN,:,NaN,:,...,d,145.44,d,146.61,d,147.71,d,150.41,d,:
32,North Macedonia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,d,138.07,d,137.88,d,141.41,d,144.23,d,:
33,Albania,:,NaN,:,NaN,:,NaN,:,NaN,:,...,d,159.73,d,159.74,d,157.57,d,155.18,d,:
34,Serbia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,d,162.4,d,163.9,d,167.1,d,169.1,d,:
35,T√ºrkiye,1.24,d,1.29,d,1.4,d,1.5,d,1.57,...,d,627.46,d,652.28,d,656.98,d,676.93,d,:

In [5]:
columns = df.columns
print(columns)

Index(['TIME', '1996-01', 'Unnamed: 2', '1996-02', 'Unnamed: 4', '1996-03',
       'Unnamed: 6', '1996-04', 'Unnamed: 8', '1996-05',
       ...
       'Unnamed: 652', '2023-03', 'Unnamed: 654', '2023-04', 'Unnamed: 656',
       '2023-05', 'Unnamed: 658', '2023-06', 'Unnamed: 660', '2023-07'],
      dtype='object', length=662)

In [6]:
columns_new = columns.tolist()

In [10]:
un_columns = [i for i in columns_new if i.startswith('Unnamed')]
print(un_columns)

['Unnamed: 2', 'Unnamed: 4', 'Unnamed: 6', 'Unnamed: 8', 'Unnamed: 10', 'Unnamed: 12', 'Unnamed: 14', 'Unnamed: 16', 'Unnamed: 18', 'Unnamed: 20', 'Unnamed: 22', 'Unnamed: 24', 'Unnamed: 26', 'Unnamed: 28', 'Unnamed: 30', 'Unnamed: 32', 'Unnamed: 34', 'Unnamed: 36', 'Unnamed: 38', 'Unnamed: 40', 'Unnamed: 42', 'Unnamed: 44', 'Unnamed: 46', 'Unnamed: 48', 'Unnamed: 50', 'Unnamed: 52', 'Unnamed: 54', 'Unnamed: 56', 'Unnamed: 58', 'Unnamed: 60', 'Unnamed: 62', 'Unnamed: 64', 'Unnamed: 66', 'Unnamed: 68', 'Unnamed: 70', 'Unnamed: 72', 'Unnamed: 74', 'Unnamed: 76', 'Unnamed: 78', 'Unnamed: 80', 'Unnamed: 82', 'Unnamed: 84', 'Unnamed: 86', 'Unnamed: 88', 'Unnamed: 90', 'Unnamed: 92', 'Unnamed: 94', 'Unnamed: 96', 'Unnamed: 98', 'Unnamed: 100', 'Unnamed: 102', 'Unnamed: 104', 'Unnamed: 106', 'Unnamed: 108', 'Unnamed: 110', 'Unnamed: 112', 'Unnamed: 114', 'Unnamed: 116', 'Unnamed: 118', 'Unnamed: 120', 'Unnamed: 122', 'Unnamed: 124', 'Unnamed: 126', 'Unnamed: 128', 'Unnamed: 130', 'Unnamed: 132', 'Unnamed: 134', 'Unnamed: 136', 'Unnamed: 138', 'Unnamed: 140', 'Unnamed: 142', 'Unnamed: 144', 'Unnamed: 146', 'Unnamed: 148', 'Unnamed: 150', 'Unnamed: 152', 'Unnamed: 154', 'Unnamed: 156', 'Unnamed: 158', 'Unnamed: 160', 'Unnamed: 162', 'Unnamed: 164', 'Unnamed: 166', 'Unnamed: 168', 'Unnamed: 170', 'Unnamed: 172', 'Unnamed: 174', 'Unnamed: 176', 'Unnamed: 178', 'Unnamed: 180', 'Unnamed: 182', 'Unnamed: 184', 'Unnamed: 186', 'Unnamed: 188', 'Unnamed: 190', 'Unnamed: 192', 'Unnamed: 194', 'Unnamed: 196', 'Unnamed: 198', 'Unnamed: 200', 'Unnamed: 202', 'Unnamed: 204', 'Unnamed: 206', 'Unnamed: 208', 'Unnamed: 210', 'Unnamed: 212', 'Unnamed: 214', 'Unnamed: 216', 'Unnamed: 218', 'Unnamed: 220', 'Unnamed: 222', 'Unnamed: 224', 'Unnamed: 226', 'Unnamed: 228', 'Unnamed: 230', 'Unnamed: 232', 'Unnamed: 234', 'Unnamed: 236', 'Unnamed: 238', 'Unnamed: 240', 'Unnamed: 242', 'Unnamed: 244', 'Unnamed: 246', 'Unnamed: 248', 'Unnamed: 250', 'Unnamed: 252', 'Unnamed: 254', 'Unnamed: 256', 'Unnamed: 258', 'Unnamed: 260', 'Unnamed: 262', 'Unnamed: 264', 'Unnamed: 266', 'Unnamed: 268', 'Unnamed: 270', 'Unnamed: 272', 'Unnamed: 274', 'Unnamed: 276', 'Unnamed: 278', 'Unnamed: 280', 'Unnamed: 282', 'Unnamed: 284', 'Unnamed: 286', 'Unnamed: 288', 'Unnamed: 290', 'Unnamed: 292', 'Unnamed: 294', 'Unnamed: 296', 'Unnamed: 298', 'Unnamed: 300', 'Unnamed: 302', 'Unnamed: 304', 'Unnamed: 306', 'Unnamed: 308', 'Unnamed: 310', 'Unnamed: 312', 'Unnamed: 314', 'Unnamed: 316', 'Unnamed: 318', 'Unnamed: 320', 'Unnamed: 322', 'Unnamed: 324', 'Unnamed: 326', 'Unnamed: 328', 'Unnamed: 330', 'Unnamed: 332', 'Unnamed: 334', 'Unnamed: 336', 'Unnamed: 338', 'Unnamed: 340', 'Unnamed: 342', 'Unnamed: 344', 'Unnamed: 346', 'Unnamed: 348', 'Unnamed: 350', 'Unnamed: 352', 'Unnamed: 354', 'Unnamed: 356', 'Unnamed: 358', 'Unnamed: 360', 'Unnamed: 362', 'Unnamed: 364', 'Unnamed: 366', 'Unnamed: 368', 'Unnamed: 370', 'Unnamed: 372', 'Unnamed: 374', 'Unnamed: 376', 'Unnamed: 378', 'Unnamed: 380', 'Unnamed: 382', 'Unnamed: 384', 'Unnamed: 386', 'Unnamed: 388', 'Unnamed: 390', 'Unnamed: 392', 'Unnamed: 394', 'Unnamed: 396', 'Unnamed: 398', 'Unnamed: 400', 'Unnamed: 402', 'Unnamed: 404', 'Unnamed: 406', 'Unnamed: 408', 'Unnamed: 410', 'Unnamed: 412', 'Unnamed: 414', 'Unnamed: 416', 'Unnamed: 418', 'Unnamed: 420', 'Unnamed: 422', 'Unnamed: 424', 'Unnamed: 426', 'Unnamed: 428', 'Unnamed: 430', 'Unnamed: 432', 'Unnamed: 434', 'Unnamed: 436', 'Unnamed: 438', 'Unnamed: 440', 'Unnamed: 442', 'Unnamed: 444', 'Unnamed: 446', 'Unnamed: 448', 'Unnamed: 450', 'Unnamed: 452', 'Unnamed: 454', 'Unnamed: 456', 'Unnamed: 458', 'Unnamed: 460', 'Unnamed: 462', 'Unnamed: 464', 'Unnamed: 466', 'Unnamed: 468', 'Unnamed: 470', 'Unnamed: 472', 'Unnamed: 474', 'Unnamed: 476', 'Unnamed: 478', 'Unnamed: 480', 'Unnamed: 482', 'Unnamed: 484', 'Unnamed: 486', 'Unnamed: 488', 'Unnamed: 490', 'Unnamed: 492', 'Unnamed: 494', 'Unnamed: 496', 'Unnamed: 498', 'Unnamed: 500', 'Unnamed: 502', 'Unnamed: 504', 'Unnamed: 506', 'Unnamed: 508', 'Unnamed: 510', 'Unnamed: 512', 'Unnamed: 514', 'Unnamed: 516', 'Unnamed: 518', 'Unnamed: 520', 'Unnamed: 522', 'Unnamed: 524', 'Unnamed: 526', 'Unnamed: 528', 'Unnamed: 530', 'Unnamed: 532', 'Unnamed: 534', 'Unnamed: 536', 'Unnamed: 538', 'Unnamed: 540', 'Unnamed: 542', 'Unnamed: 544', 'Unnamed: 546', 'Unnamed: 548', 'Unnamed: 550', 'Unnamed: 552', 'Unnamed: 554', 'Unnamed: 556', 'Unnamed: 558', 'Unnamed: 560', 'Unnamed: 562', 'Unnamed: 564', 'Unnamed: 566', 'Unnamed: 568', 'Unnamed: 570', 'Unnamed: 572', 'Unnamed: 574', 'Unnamed: 576', 'Unnamed: 578', 'Unnamed: 580', 'Unnamed: 582', 'Unnamed: 584', 'Unnamed: 586', 'Unnamed: 588', 'Unnamed: 590', 'Unnamed: 592', 'Unnamed: 594', 'Unnamed: 596', 'Unnamed: 598', 'Unnamed: 600', 'Unnamed: 602', 'Unnamed: 604', 'Unnamed: 606', 'Unnamed: 608', 'Unnamed: 610', 'Unnamed: 612', 'Unnamed: 614', 'Unnamed: 616', 'Unnamed: 618', 'Unnamed: 620', 'Unnamed: 622', 'Unnamed: 624', 'Unnamed: 626', 'Unnamed: 628', 'Unnamed: 630', 'Unnamed: 632', 'Unnamed: 634', 'Unnamed: 636', 'Unnamed: 638', 'Unnamed: 640', 'Unnamed: 642', 'Unnamed: 644', 'Unnamed: 646', 'Unnamed: 648', 'Unnamed: 650', 'Unnamed: 652', 'Unnamed: 654', 'Unnamed: 656', 'Unnamed: 658', 'Unnamed: 660']

In [12]:
df_new = df.drop(un_columns, axis = 1)
df_new

,TIME,1996-01,1996-02,1996-03,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,...,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07
0,Belgium,65.83,65.96,66.42,66.69,67.15,67.09,66.42,65.83,65.56,...,122.24,124.53,125.69,130.26,132.65,135.76,133.49,134.04,134.21,:
1,Bulgaria,:,:,:,:,:,:,:,:,:,...,154.13,156.72,158.02,160.51,164.37,165.84,166.06,166.73,165.76,:
2,Czechia,67.7,68.1,68.9,69.6,70.4,71.2,70.2,68.9,69,...,142.4,145.1,145.7,151.2,152.2,152.8,150.3,151.7,151.7,:
3,Denmark,68.2,68.4,68.7,68.8,69.2,69.4,69.9,70,69.9,...,122.9,123.5,121.2,124.3,127.2,128.3,127.6,128.3,129.7,:
4,Germany,75.7,76.3,76.7,77,76.8,76.8,76.7,75.9,75.3,...,134.9,136.6,137.6,139.7,143,144.9,144.2,144,144,:
5,Estonia,48.18,50.55,51.51,52.44,52.72,52.7,52.57,50.64,50.49,...,149.19,152.47,153.97,157.14,160.05,161.41,163.3,163.17,165.32,:
6,Ireland,79,79.3,79.7,80.1,80.5,80.6,80.6,80.5,80.2,...,102.5,103.3,104.4,105.2,106.4,107.5,108.3,108.7,108.8,:
7,Greece,60.18,60.87,62.36,63.24,64.11,63.49,61.49,61.06,61.99,...,120.47,121.76,121.83,123,124.75,125.02,124.94,127.48,131.67,:
8,Spain,63.99,63.87,63.8,64.38,64.83,64.45,64.45,64.7,64.9,...,128.15,128.78,130.82,131.32,133.9,135.33,135.69,136.2,136.54,:
9,France,72.8,72.94,73.55,73.5,74.21,73.85,73.65,72.63,72.78,...,122.63,123.25,123.85,126.03,128.3,130.76,131.46,131.88,132.21,:
10,Croatia,:,:,:,:,:,:,:,:,:,...,129.51,130.98,132.69,134.6,135.06,136.58,137.87,140.06,141.95,:
11,Italy,68.9,69.1,69.4,70,70.5,70.7,70.5,70.3,70.1,...,120.9,122.1,122.4,123.6,125.6,126.6,127.1,128.4,128.8,:
12,Cyprus,51.82,51.99,53.63,52.99,52.88,51.96,52.3,53.34,53.5,...,118.03,118.93,115.52,116.52,120.69,119.66,120.71,122.81,121.91,:
13,Latvia,44.57,45.62,46.73,46.95,47.04,47.58,46.93,45.68,45.64,...,151.44,153.72,155.35,157.37,159.32,161.7,162.38,162.25,162.09,:
14,Lithuania,55.99,57.95,59.88,61.11,61.31,61.28,60.78,60.42,60.87,...,158.54,161.79,163.76,166.25,167.35,168.6,169.84,169.88,168.38,:
15,Luxembourg,64.11,64.04,64.17,64.3,64.37,64.56,64.69,64.69,64.43,...,124.19,124.52,125.19,127.25,129.61,131.3,132.1,132.52,132.89,:
16,Hungary,29.98,30.55,31.03,31.31,31.56,31.66,31.63,31.37,32.1,...,180.05,186.84,190.52,195.53,198.67,201.39,200.43,200.18,198.7,:
17,Malta,56.83,57.83,59.06,59.63,59.37,58.71,58.1,58.73,59.42,...,133.54,134.19,134.78,134.93,137.7,138.48,138.67,140.14,141.5,:
18,Netherlands,74.79,75.02,76.36,76.21,75.09,74.57,74.49,73.22,73.6,...,126.42,128.89,131.55,133.6,136.39,136.89,136.63,137.75,138.15,:
19,Austria,68.07,68.2,68.95,68.61,68.34,68.54,68.2,67.12,66.85,...,125.61,126.97,128.69,129.56,132.08,132.05,133.11,133.4,134.36,:
20,Poland,47.5,48.4,49.5,50.9,51.4,51.7,50.9,50.6,52.3,...,146.4,148.6,150.9,154.3,157.5,161.5,162.3,163.5,163.1,:
21,Portugal,72.47,72.91,72.99,74.32,74.91,74.17,74.39,74.68,74.39,...,125.92,128.08,128.99,131.39,133.4,134.69,134.55,130.4,130.8,:
22,Romania,4.39,4.48,4.54,4.66,4.99,5.02,5.29,5.39,5.51,...,146.32,148.55,150.44,152.64,155.64,158.95,160.7,161.88,161.44,:
23,Slovenia,44.02,45,46.2,47.36,47.55,47.27,47.04,45.55,45.55,...,130.34,131.7,133.95,136.87,138.82,140.43,140.31,141.41,140.63,:
24,Slovakia,57,56.6,56.55,56.71,56.87,56.22,56.61,56.91,58.31,...,145.29,148.05,149.53,153.75,156.54,159.8,160.18,160.82,160.73,:
25,Finland,68.19,68.74,69.15,69.22,69.5,69.15,69.5,68.67,68.47,...,120.02,121.07,120.68,122.58,125.4,126.26,124.72,125.02,124.46,:
26,Sweden,72.04,72.23,73.33,73.53,73.53,73.42,74.33,73.37,72.42,...,132.07,132.81,133.72,136.81,140.54,142.26,140.76,140.13,140.45,:
27,Iceland,44.65,44.79,45.2,45.51,45.7,45.42,45.33,46.11,45.88,...,125.46,126.35,127.24,129.65,132.1,133.06,135.05,136.13,136.97,:
28,Norway,68.6,68.6,68.8,69,69.5,69.9,71.2,70.6,70.3,...,119.2,118.8,116.9,118.3,120.2,118.3,121.3,123.8,126.7,:
29,Switzerland,:,:,:,:,:,:,:,:,:,...,104.72,104.16,103.24,104.68,105.79,106.53,105.67,107.45,108.48,:
30,United Kingdom,64.9,65.6,66.1,66.1,66.6,66.5,65.6,66.4,65.7,...,:,:,:,:,:,:,:,:,:,:
31,Montenegro,:,:,:,:,:,:,:,:,:,...,143.96,145.02,145.73,147.74,149.41,145.44,146.61,147.71,150.41,:
32,North Macedonia,:,:,:,:,:,:,:,:,:,...,139.7,139.96,137.18,136.31,137.73,138.07,137.88,141.41,144.23,:
33,Albania,:,:,:,:,:,:,:,:,:,...,145.36,144.28,146.11,150.17,156.08,159.73,159.74,157.57,155.18,:
34,Serbia,:,:,:,:,:,:,:,:,:,...,149.4,151.2,152.7,155.2,159.4,162.4,163.9,167.1,169.1,:
35,T√ºrkiye,1.24,1.29,1.4,1.5,1.57,1.56,1.53,1.61,1.67,...,489.54,518.13,527.85,562.78,604.09,627.46,652.28,656.98,676.93,:

In [17]:
df_new.to_csv("Food_and_non_alcoholic_beverages.csv" ,index = False)