In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel("C:/Users/tom/Downloads/output_price_grain_starch.xlsm")
df

,Country,1996-01,Unnamed: 2,1996-02,Unnamed: 4,1996-03,Unnamed: 6,1996-04,Unnamed: 8,1996-05,...,Unnamed: 652,2023-03,Unnamed: 654,2023-04,Unnamed: 656,2023-05,Unnamed: 658,2023-06,Unnamed: 660,2023-07
0,Belgium,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
1,Bulgaria,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,167,NaN,164.5,NaN,164.8,NaN,160.9,NaN,:
2,Czechia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,170,NaN,167.4,NaN,160.1,NaN,156.1,NaN,:
3,Denmark,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
4,Germany,87.3,NaN,87.4,NaN,87.7,NaN,87.8,NaN,88.8,...,NaN,161.8,NaN,158.7,NaN,156.1,NaN,155.7,NaN,:
5,Estonia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
6,Ireland,:,NaN,:,NaN,:,NaN,:,NaN,:,...,c,:,c,:,c,:,c,:,c,:
7,Greece,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,129,NaN,128.7,NaN,126.4,NaN,125,NaN,:
8,Spain,81.4,NaN,81.6,NaN,81.9,NaN,82,NaN,82.6,...,NaN,172.8,NaN,170.4,p,165.4,p,164.2,p,:
9,France,:,c,:,c,:,c,:,c,:,...,NaN,164.7,NaN,162.9,p,160,p,158.7,p,:
10,Croatia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,123.5,NaN,124,NaN,123.8,NaN,123.1,NaN,121.9
11,Italy,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,160.6,NaN,156.9,NaN,151.3,NaN,145.2,p,:
12,Cyprus,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
13,Latvia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
14,Lithuania,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,181.6,NaN,188.5,NaN,188.3,NaN,182.7,p,:
15,Luxembourg,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
16,Hungary,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,290.4,NaN,271.6,NaN,263.6,NaN,246.8,NaN,:
17,Malta,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
18,Netherlands,:,NaN,:,NaN,:,NaN,:,NaN,:,...,p,194.2,p,193.7,p,194.5,p,194,p,:
19,Austria,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
20,Poland,:,NaN,:,NaN,:,NaN,:,NaN,:,...,s,186.2,s,177.9,s,173.3,s,171.4,s,:
21,Portugal,:,NaN,:,NaN,:,NaN,:,NaN,:,...,c,:,c,:,c,:,c,145.3,NaN,:
22,Romania,:,NaN,:,NaN,:,NaN,:,NaN,:,...,c,:,c,:,c,:,c,:,NaN,:
23,Slovenia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,144.3,NaN,143.8,NaN,144.9,NaN,144.2,NaN,:
24,Slovakia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,c,:,c,:,c,:,c,:,c,:
25,Finland,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,145.5,NaN,144.7,NaN,142.2,NaN,141.4,NaN,:
26,Sweden,74.1,NaN,74.8,NaN,74.8,NaN,76,NaN,76.2,...,NaN,169.4,NaN,163.9,NaN,158.9,NaN,159,NaN,:
27,Norway,:,NaN,:,NaN,:,NaN,:,NaN,:,...,c,:,c,:,c,:,c,:,c,:
28,Switzerland,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
29,United Kingdom,76.5,NaN,76.7,NaN,76.3,NaN,76.7,NaN,76.7,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
30,Montenegro,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
31,North Macedonia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
32,Albania,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
33,Serbia,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,:,NaN,:,NaN,:,NaN,:,NaN,:
34,Türkiye,:,NaN,:,NaN,:,NaN,:,NaN,:,...,NaN,817,NaN,820.3,NaN,842.5,NaN,871.1,NaN,:

In [5]:
spalten_liste = df.columns.tolist()
spalten_liste

['Country',
 '1996-01',
 'Unnamed: 2',
 '1996-02',
 'Unnamed: 4',
 '1996-03',
 'Unnamed: 6',
 '1996-04',
 'Unnamed: 8',
 '1996-05',
 'Unnamed: 10',
 '1996-06',
 'Unnamed: 12',
 '1996-07',
 'Unnamed: 14',
 '1996-08',
 'Unnamed: 16',
 '1996-09',
 'Unnamed: 18',
 '1996-10',
 'Unnamed: 20',
 '1996-11',
 'Unnamed: 22',
 '1996-12',
 'Unnamed: 24',
 '1997-01',
 'Unnamed: 26',
 '1997-02',
 'Unnamed: 28',
 '1997-03',
 'Unnamed: 30',
 '1997-04',
 'Unnamed: 32',
 '1997-05',
 'Unnamed: 34',
 '1997-06',
 'Unnamed: 36',
 '1997-07',
 'Unnamed: 38',
 '1997-08',
 'Unnamed: 40',
 '1997-09',
 'Unnamed: 42',
 '1997-10',
 'Unnamed: 44',
 '1997-11',
 'Unnamed: 46',
 '1997-12',
 'Unnamed: 48',
 '1998-01',
 'Unnamed: 50',
 '1998-02',
 'Unnamed: 52',
 '1998-03',
 'Unnamed: 54',
 '1998-04',
 'Unnamed: 56',
 '1998-05',
 'Unnamed: 58',
 '1998-06',
 'Unnamed: 60',
 '1998-07',
 'Unnamed: 62',
 '1998-08',
 'Unnamed: 64',
 '1998-09',
 'Unnamed: 66',
 '1998-10',
 'Unnamed: 68',
 '1998-11',
 'Unnamed: 70',
 '1998-12',
 'Unnamed: 72',
 '1999-01',
 'Unnamed: 74',
 '1999-02',
 'Unnamed: 76',
 '1999-03',
 'Unnamed: 78',
 '1999-04',
 'Unnamed: 80',
 '1999-05',
 'Unnamed: 82',
 '1999-06',
 'Unnamed: 84',
 '1999-07',
 'Unnamed: 86',
 '1999-08',
 'Unnamed: 88',
 '1999-09',
 'Unnamed: 90',
 '1999-10',
 'Unnamed: 92',
 '1999-11',
 'Unnamed: 94',
 '1999-12',
 'Unnamed: 96',
 '2000-01',
 'Unnamed: 98',
 '2000-02',
 'Unnamed: 100',
 '2000-03',
 'Unnamed: 102',
 '2000-04',
 'Unnamed: 104',
 '2000-05',
 'Unnamed: 106',
 '2000-06',
 'Unnamed: 108',
 '2000-07',
 'Unnamed: 110',
 '2000-08',
 'Unnamed: 112',
 '2000-09',
 'Unnamed: 114',
 '2000-10',
 'Unnamed: 116',
 '2000-11',
 'Unnamed: 118',
 '2000-12',
 'Unnamed: 120',
 '2001-01',
 'Unnamed: 122',
 '2001-02',
 'Unnamed: 124',
 '2001-03',
 'Unnamed: 126',
 '2001-04',
 'Unnamed: 128',
 '2001-05',
 'Unnamed: 130',
 '2001-06',
 'Unnamed: 132',
 '2001-07',
 'Unnamed: 134',
 '2001-08',
 'Unnamed: 136',
 '2001-09',
 'Unnamed: 138',
 '2001-10',
 'Unnamed: 140',
 '2001-11',
 'Unnamed: 142',
 '2001-12',
 'Unnamed: 144',
 '2002-01',
 'Unnamed: 146',
 '2002-02',
 'Unnamed: 148',
 '2002-03',
 'Unnamed: 150',
 '2002-04',
 'Unnamed: 152',
 '2002-05',
 'Unnamed: 154',
 '2002-06',
 'Unnamed: 156',
 '2002-07',
 'Unnamed: 158',
 '2002-08',
 'Unnamed: 160',
 '2002-09',
 'Unnamed: 162',
 '2002-10',
 'Unnamed: 164',
 '2002-11',
 'Unnamed: 166',
 '2002-12',
 'Unnamed: 168',
 '2003-01',
 'Unnamed: 170',
 '2003-02',
 'Unnamed: 172',
 '2003-03',
 'Unnamed: 174',
 '2003-04',
 'Unnamed: 176',
 '2003-05',
 'Unnamed: 178',
 '2003-06',
 'Unnamed: 180',
 '2003-07',
 'Unnamed: 182',
 '2003-08',
 'Unnamed: 184',
 '2003-09',
 'Unnamed: 186',
 '2003-10',
 'Unnamed: 188',
 '2003-11',
 'Unnamed: 190',
 '2003-12',
 'Unnamed: 192',
 '2004-01',
 'Unnamed: 194',
 '2004-02',
 'Unnamed: 196',
 '2004-03',
 'Unnamed: 198',
 '2004-04',
 'Unnamed: 200',
 '2004-05',
 'Unnamed: 202',
 '2004-06',
 'Unnamed: 204',
 '2004-07',
 'Unnamed: 206',
 '2004-08',
 'Unnamed: 208',
 '2004-09',
 'Unnamed: 210',
 '2004-10',
 'Unnamed: 212',
 '2004-11',
 'Unnamed: 214',
 '2004-12',
 'Unnamed: 216',
 '2005-01',
 'Unnamed: 218',
 '2005-02',
 'Unnamed: 220',
 '2005-03',
 'Unnamed: 222',
 '2005-04',
 'Unnamed: 224',
 '2005-05',
 'Unnamed: 226',
 '2005-06',
 'Unnamed: 228',
 '2005-07',
 'Unnamed: 230',
 '2005-08',
 'Unnamed: 232',
 '2005-09',
 'Unnamed: 234',
 '2005-10',
 'Unnamed: 236',
 '2005-11',
 'Unnamed: 238',
 '2005-12',
 'Unnamed: 240',
 '2006-01',
 'Unnamed: 242',
 '2006-02',
 'Unnamed: 244',
 '2006-03',
 'Unnamed: 246',
 '2006-04',
 'Unnamed: 248',
 '2006-05',
 'Unnamed: 250',
 '2006-06',
 'Unnamed: 252',
 '2006-07',
 'Unnamed: 254',
 '2006-08',
 'Unnamed: 256',
 '2006-09',
 'Unnamed: 258',
 '2006-10',
 'Unnamed: 260',
 '2006-11',
 'Unnamed: 262',
 '2006-12',
 'Unnamed: 264',
 '2007-01',
 'Unnamed: 266',
 '2007-02',
 'Unnamed: 268',
 '2007-03',
 'Unnamed: 270',
 '2007-04',
 'Unnamed: 272',
 '2007-05',
 'Unnamed: 274',
 '2007-06',
 'Unnamed: 276',
 '2007-07',
 'Unnamed: 278',
 '2007-08',
 'Unnamed: 280',
 '2007-09',
 'Unnamed: 282',
 '2007-10',
 'Unnamed: 284',
 '2007-11',
 'Unnamed: 286',
 '2007-12',
 'Unnamed: 288',
 '2008-01',
 'Unnamed: 290',
 '2008-02',
 'Unnamed: 292',
 '2008-03',
 'Unnamed: 294',
 '2008-04',
 'Unnamed: 296',
 '2008-05',
 'Unnamed: 298',
 '2008-06',
 'Unnamed: 300',
 '2008-07',
 'Unnamed: 302',
 '2008-08',
 'Unnamed: 304',
 '2008-09',
 'Unnamed: 306',
 '2008-10',
 'Unnamed: 308',
 '2008-11',
 'Unnamed: 310',
 '2008-12',
 'Unnamed: 312',
 '2009-01',
 'Unnamed: 314',
 '2009-02',
 'Unnamed: 316',
 '2009-03',
 'Unnamed: 318',
 '2009-04',
 'Unnamed: 320',
 '2009-05',
 'Unnamed: 322',
 '2009-06',
 'Unnamed: 324',
 '2009-07',
 'Unnamed: 326',
 '2009-08',
 'Unnamed: 328',
 '2009-09',
 'Unnamed: 330',
 '2009-10',
 'Unnamed: 332',
 '2009-11',
 'Unnamed: 334',
 '2009-12',
 'Unnamed: 336',
 '2010-01',
 'Unnamed: 338',
 '2010-02',
 'Unnamed: 340',
 '2010-03',
 'Unnamed: 342',
 '2010-04',
 'Unnamed: 344',
 '2010-05',
 'Unnamed: 346',
 '2010-06',
 'Unnamed: 348',
 '2010-07',
 'Unnamed: 350',
 '2010-08',
 'Unnamed: 352',
 '2010-09',
 'Unnamed: 354',
 '2010-10',
 'Unnamed: 356',
 '2010-11',
 'Unnamed: 358',
 '2010-12',
 'Unnamed: 360',
 '2011-01',
 'Unnamed: 362',
 '2011-02',
 'Unnamed: 364',
 '2011-03',
 'Unnamed: 366',
 '2011-04',
 'Unnamed: 368',
 '2011-05',
 'Unnamed: 370',
 '2011-06',
 'Unnamed: 372',
 '2011-07',
 'Unnamed: 374',
 '2011-08',
 'Unnamed: 376',
 '2011-09',
 'Unnamed: 378',
 '2011-10',
 'Unnamed: 380',
 '2011-11',
 'Unnamed: 382',
 '2011-12',
 'Unnamed: 384',
 '2012-01',
 'Unnamed: 386',
 '2012-02',
 'Unnamed: 388',
 '2012-03',
 'Unnamed: 390',
 '2012-04',
 'Unnamed: 392',
 '2012-05',
 'Unnamed: 394',
 '2012-06',
 'Unnamed: 396',
 '2012-07',
 'Unnamed: 398',
 '2012-08',
 'Unnamed: 400',
 '2012-09',
 'Unnamed: 402',
 '2012-10',
 'Unnamed: 404',
 '2012-11',
 'Unnamed: 406',
 '2012-12',
 'Unnamed: 408',
 '2013-01',
 'Unnamed: 410',
 '2013-02',
 'Unnamed: 412',
 '2013-03',
 'Unnamed: 414',
 '2013-04',
 'Unnamed: 416',
 '2013-05',
 'Unnamed: 418',
 '2013-06',
 'Unnamed: 420',
 '2013-07',
 'Unnamed: 422',
 '2013-08',
 'Unnamed: 424',
 '2013-09',
 'Unnamed: 426',
 '2013-10',
 'Unnamed: 428',
 '2013-11',
 'Unnamed: 430',
 '2013-12',
 'Unnamed: 432',
 '2014-01',
 'Unnamed: 434',
 '2014-02',
 'Unnamed: 436',
 '2014-03',
 'Unnamed: 438',
 '2014-04',
 'Unnamed: 440',
 '2014-05',
 'Unnamed: 442',
 '2014-06',
 'Unnamed: 444',
 '2014-07',
 'Unnamed: 446',
 '2014-08',
 'Unnamed: 448',
 '2014-09',
 'Unnamed: 450',
 '2014-10',
 'Unnamed: 452',
 '2014-11',
 'Unnamed: 454',
 '2014-12',
 'Unnamed: 456',
 '2015-01',
 'Unnamed: 458',
 '2015-02',
 'Unnamed: 460',
 '2015-03',
 'Unnamed: 462',
 '2015-04',
 'Unnamed: 464',
 '2015-05',
 'Unnamed: 466',
 '2015-06',
 'Unnamed: 468',
 '2015-07',
 'Unnamed: 470',
 '2015-08',
 'Unnamed: 472',
 '2015-09',
 'Unnamed: 474',
 '2015-10',
 'Unnamed: 476',
 '2015-11',
 'Unnamed: 478',
 '2015-12',
 'Unnamed: 480',
 '2016-01',
 'Unnamed: 482',
 '2016-02',
 'Unnamed: 484',
 '2016-03',
 'Unnamed: 486',
 '2016-04',
 'Unnamed: 488',
 '2016-05',
 'Unnamed: 490',
 '2016-06',
 'Unnamed: 492',
 '2016-07',
 'Unnamed: 494',
 '2016-08',
 'Unnamed: 496',
 '2016-09',
 'Unnamed: 498',
 '2016-10',
 'Unnamed: 500',
 '2016-11',
 'Unnamed: 502',
 '2016-12',
 'Unnamed: 504',
 '2017-01',
 'Unnamed: 506',
 '2017-02',
 'Unnamed: 508',
 '2017-03',
 'Unnamed: 510',
 '2017-04',
 'Unnamed: 512',
 '2017-05',
 'Unnamed: 514',
 '2017-06',
 'Unnamed: 516',
 '2017-07',
 'Unnamed: 518',
 '2017-08',
 'Unnamed: 520',
 '2017-09',
 'Unnamed: 522',
 '2017-10',
 'Unnamed: 524',
 '2017-11',
 'Unnamed: 526',
 '2017-12',
 'Unnamed: 528',
 '2018-01',
 'Unnamed: 530',
 '2018-02',
 'Unnamed: 532',
 '2018-03',
 'Unnamed: 534',
 '2018-04',
 'Unnamed: 536',
 '2018-05',
 'Unnamed: 538',
 '2018-06',
 'Unnamed: 540',
 '2018-07',
 'Unnamed: 542',
 '2018-08',
 'Unnamed: 544',
 '2018-09',
 'Unnamed: 546',
 '2018-10',
 'Unnamed: 548',
 '2018-11',
 'Unnamed: 550',
 '2018-12',
 'Unnamed: 552',
 '2019-01',
 'Unnamed: 554',
 '2019-02',
 'Unnamed: 556',
 '2019-03',
 'Unnamed: 558',
 '2019-04',
 'Unnamed: 560',
 '2019-05',
 'Unnamed: 562',
 '2019-06',
 'Unnamed: 564',
 '2019-07',
 'Unnamed: 566',
 '2019-08',
 'Unnamed: 568',
 '2019-09',
 'Unnamed: 570',
 '2019-10',
 'Unnamed: 572',
 '2019-11',
 'Unnamed: 574',
 '2019-12',
 'Unnamed: 576',
 '2020-01',
 'Unnamed: 578',
 '2020-02',
 'Unnamed: 580',
 '2020-03',
 'Unnamed: 582',
 '2020-04',
 'Unnamed: 584',
 '2020-05',
 'Unnamed: 586',
 '2020-06',
 'Unnamed: 588',
 '2020-07',
 'Unnamed: 590',
 '2020-08',
 'Unnamed: 592',
 '2020-09',
 'Unnamed: 594',
 '2020-10',
 'Unnamed: 596',
 '2020-11',
 'Unnamed: 598',
 '2020-12',
 'Unnamed: 600',
 '2021-01',
 'Unnamed: 602',
 '2021-02',
 'Unnamed: 604',
 '2021-03',
 'Unnamed: 606',
 '2021-04',
 'Unnamed: 608',
 '2021-05',
 'Unnamed: 610',
 '2021-06',
 'Unnamed: 612',
 '2021-07',
 'Unnamed: 614',
 '2021-08',
 'Unnamed: 616',
 '2021-09',
 'Unnamed: 618',
 '2021-10',
 'Unnamed: 620',
 '2021-11',
 'Unnamed: 622',
 '2021-12',
 'Unnamed: 624',
 '2022-01',
 'Unnamed: 626',
 '2022-02',
 'Unnamed: 628',
 '2022-03',
 'Unnamed: 630',
 '2022-04',
 'Unnamed: 632',
 '2022-05',
 'Unnamed: 634',
 '2022-06',
 'Unnamed: 636',
 '2022-07',
 'Unnamed: 638',
 '2022-08',
 'Unnamed: 640',
 '2022-09',
 'Unnamed: 642',
 '2022-10',
 'Unnamed: 644',
 '2022-11',
 'Unnamed: 646',
 '2022-12',
 'Unnamed: 648',
 '2023-01',
 'Unnamed: 650',
 '2023-02',
 'Unnamed: 652',
 '2023-03',
 'Unnamed: 654',
 '2023-04',
 'Unnamed: 656',
 '2023-05',
 'Unnamed: 658',
 '2023-06',
 'Unnamed: 660',
 '2023-07']

In [6]:
filt_liste = [i for i in spalten_liste if i.startswith('Unnamed')]
filt_liste

['Unnamed: 2',
 'Unnamed: 4',
 'Unnamed: 6',
 'Unnamed: 8',
 'Unnamed: 10',
 'Unnamed: 12',
 'Unnamed: 14',
 'Unnamed: 16',
 'Unnamed: 18',
 'Unnamed: 20',
 'Unnamed: 22',
 'Unnamed: 24',
 'Unnamed: 26',
 'Unnamed: 28',
 'Unnamed: 30',
 'Unnamed: 32',
 'Unnamed: 34',
 'Unnamed: 36',
 'Unnamed: 38',
 'Unnamed: 40',
 'Unnamed: 42',
 'Unnamed: 44',
 'Unnamed: 46',
 'Unnamed: 48',
 'Unnamed: 50',
 'Unnamed: 52',
 'Unnamed: 54',
 'Unnamed: 56',
 'Unnamed: 58',
 'Unnamed: 60',
 'Unnamed: 62',
 'Unnamed: 64',
 'Unnamed: 66',
 'Unnamed: 68',
 'Unnamed: 70',
 'Unnamed: 72',
 'Unnamed: 74',
 'Unnamed: 76',
 'Unnamed: 78',
 'Unnamed: 80',
 'Unnamed: 82',
 'Unnamed: 84',
 'Unnamed: 86',
 'Unnamed: 88',
 'Unnamed: 90',
 'Unnamed: 92',
 'Unnamed: 94',
 'Unnamed: 96',
 'Unnamed: 98',
 'Unnamed: 100',
 'Unnamed: 102',
 'Unnamed: 104',
 'Unnamed: 106',
 'Unnamed: 108',
 'Unnamed: 110',
 'Unnamed: 112',
 'Unnamed: 114',
 'Unnamed: 116',
 'Unnamed: 118',
 'Unnamed: 120',
 'Unnamed: 122',
 'Unnamed: 124',
 'Unnamed: 126',
 'Unnamed: 128',
 'Unnamed: 130',
 'Unnamed: 132',
 'Unnamed: 134',
 'Unnamed: 136',
 'Unnamed: 138',
 'Unnamed: 140',
 'Unnamed: 142',
 'Unnamed: 144',
 'Unnamed: 146',
 'Unnamed: 148',
 'Unnamed: 150',
 'Unnamed: 152',
 'Unnamed: 154',
 'Unnamed: 156',
 'Unnamed: 158',
 'Unnamed: 160',
 'Unnamed: 162',
 'Unnamed: 164',
 'Unnamed: 166',
 'Unnamed: 168',
 'Unnamed: 170',
 'Unnamed: 172',
 'Unnamed: 174',
 'Unnamed: 176',
 'Unnamed: 178',
 'Unnamed: 180',
 'Unnamed: 182',
 'Unnamed: 184',
 'Unnamed: 186',
 'Unnamed: 188',
 'Unnamed: 190',
 'Unnamed: 192',
 'Unnamed: 194',
 'Unnamed: 196',
 'Unnamed: 198',
 'Unnamed: 200',
 'Unnamed: 202',
 'Unnamed: 204',
 'Unnamed: 206',
 'Unnamed: 208',
 'Unnamed: 210',
 'Unnamed: 212',
 'Unnamed: 214',
 'Unnamed: 216',
 'Unnamed: 218',
 'Unnamed: 220',
 'Unnamed: 222',
 'Unnamed: 224',
 'Unnamed: 226',
 'Unnamed: 228',
 'Unnamed: 230',
 'Unnamed: 232',
 'Unnamed: 234',
 'Unnamed: 236',
 'Unnamed: 238',
 'Unnamed: 240',
 'Unnamed: 242',
 'Unnamed: 244',
 'Unnamed: 246',
 'Unnamed: 248',
 'Unnamed: 250',
 'Unnamed: 252',
 'Unnamed: 254',
 'Unnamed: 256',
 'Unnamed: 258',
 'Unnamed: 260',
 'Unnamed: 262',
 'Unnamed: 264',
 'Unnamed: 266',
 'Unnamed: 268',
 'Unnamed: 270',
 'Unnamed: 272',
 'Unnamed: 274',
 'Unnamed: 276',
 'Unnamed: 278',
 'Unnamed: 280',
 'Unnamed: 282',
 'Unnamed: 284',
 'Unnamed: 286',
 'Unnamed: 288',
 'Unnamed: 290',
 'Unnamed: 292',
 'Unnamed: 294',
 'Unnamed: 296',
 'Unnamed: 298',
 'Unnamed: 300',
 'Unnamed: 302',
 'Unnamed: 304',
 'Unnamed: 306',
 'Unnamed: 308',
 'Unnamed: 310',
 'Unnamed: 312',
 'Unnamed: 314',
 'Unnamed: 316',
 'Unnamed: 318',
 'Unnamed: 320',
 'Unnamed: 322',
 'Unnamed: 324',
 'Unnamed: 326',
 'Unnamed: 328',
 'Unnamed: 330',
 'Unnamed: 332',
 'Unnamed: 334',
 'Unnamed: 336',
 'Unnamed: 338',
 'Unnamed: 340',
 'Unnamed: 342',
 'Unnamed: 344',
 'Unnamed: 346',
 'Unnamed: 348',
 'Unnamed: 350',
 'Unnamed: 352',
 'Unnamed: 354',
 'Unnamed: 356',
 'Unnamed: 358',
 'Unnamed: 360',
 'Unnamed: 362',
 'Unnamed: 364',
 'Unnamed: 366',
 'Unnamed: 368',
 'Unnamed: 370',
 'Unnamed: 372',
 'Unnamed: 374',
 'Unnamed: 376',
 'Unnamed: 378',
 'Unnamed: 380',
 'Unnamed: 382',
 'Unnamed: 384',
 'Unnamed: 386',
 'Unnamed: 388',
 'Unnamed: 390',
 'Unnamed: 392',
 'Unnamed: 394',
 'Unnamed: 396',
 'Unnamed: 398',
 'Unnamed: 400',
 'Unnamed: 402',
 'Unnamed: 404',
 'Unnamed: 406',
 'Unnamed: 408',
 'Unnamed: 410',
 'Unnamed: 412',
 'Unnamed: 414',
 'Unnamed: 416',
 'Unnamed: 418',
 'Unnamed: 420',
 'Unnamed: 422',
 'Unnamed: 424',
 'Unnamed: 426',
 'Unnamed: 428',
 'Unnamed: 430',
 'Unnamed: 432',
 'Unnamed: 434',
 'Unnamed: 436',
 'Unnamed: 438',
 'Unnamed: 440',
 'Unnamed: 442',
 'Unnamed: 444',
 'Unnamed: 446',
 'Unnamed: 448',
 'Unnamed: 450',
 'Unnamed: 452',
 'Unnamed: 454',
 'Unnamed: 456',
 'Unnamed: 458',
 'Unnamed: 460',
 'Unnamed: 462',
 'Unnamed: 464',
 'Unnamed: 466',
 'Unnamed: 468',
 'Unnamed: 470',
 'Unnamed: 472',
 'Unnamed: 474',
 'Unnamed: 476',
 'Unnamed: 478',
 'Unnamed: 480',
 'Unnamed: 482',
 'Unnamed: 484',
 'Unnamed: 486',
 'Unnamed: 488',
 'Unnamed: 490',
 'Unnamed: 492',
 'Unnamed: 494',
 'Unnamed: 496',
 'Unnamed: 498',
 'Unnamed: 500',
 'Unnamed: 502',
 'Unnamed: 504',
 'Unnamed: 506',
 'Unnamed: 508',
 'Unnamed: 510',
 'Unnamed: 512',
 'Unnamed: 514',
 'Unnamed: 516',
 'Unnamed: 518',
 'Unnamed: 520',
 'Unnamed: 522',
 'Unnamed: 524',
 'Unnamed: 526',
 'Unnamed: 528',
 'Unnamed: 530',
 'Unnamed: 532',
 'Unnamed: 534',
 'Unnamed: 536',
 'Unnamed: 538',
 'Unnamed: 540',
 'Unnamed: 542',
 'Unnamed: 544',
 'Unnamed: 546',
 'Unnamed: 548',
 'Unnamed: 550',
 'Unnamed: 552',
 'Unnamed: 554',
 'Unnamed: 556',
 'Unnamed: 558',
 'Unnamed: 560',
 'Unnamed: 562',
 'Unnamed: 564',
 'Unnamed: 566',
 'Unnamed: 568',
 'Unnamed: 570',
 'Unnamed: 572',
 'Unnamed: 574',
 'Unnamed: 576',
 'Unnamed: 578',
 'Unnamed: 580',
 'Unnamed: 582',
 'Unnamed: 584',
 'Unnamed: 586',
 'Unnamed: 588',
 'Unnamed: 590',
 'Unnamed: 592',
 'Unnamed: 594',
 'Unnamed: 596',
 'Unnamed: 598',
 'Unnamed: 600',
 'Unnamed: 602',
 'Unnamed: 604',
 'Unnamed: 606',
 'Unnamed: 608',
 'Unnamed: 610',
 'Unnamed: 612',
 'Unnamed: 614',
 'Unnamed: 616',
 'Unnamed: 618',
 'Unnamed: 620',
 'Unnamed: 622',
 'Unnamed: 624',
 'Unnamed: 626',
 'Unnamed: 628',
 'Unnamed: 630',
 'Unnamed: 632',
 'Unnamed: 634',
 'Unnamed: 636',
 'Unnamed: 638',
 'Unnamed: 640',
 'Unnamed: 642',
 'Unnamed: 644',
 'Unnamed: 646',
 'Unnamed: 648',
 'Unnamed: 650',
 'Unnamed: 652',
 'Unnamed: 654',
 'Unnamed: 656',
 'Unnamed: 658',
 'Unnamed: 660']

In [7]:
df_new = df.drop(filt_liste, axis =1)
df_new

,Country,1996-01,1996-02,1996-03,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,...,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07
0,Belgium,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
1,Bulgaria,:,:,:,:,:,:,:,:,:,...,165.7,166,166.2,167,169.5,167,164.5,164.8,160.9,:
2,Czechia,:,:,:,:,:,:,:,:,:,...,173.3,173.6,173.5,172.7,171,170,167.4,160.1,156.1,:
3,Denmark,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
4,Germany,87.3,87.4,87.7,87.8,88.8,89.4,89.7,89.8,89.2,...,154,159,158.4,160.1,162.1,161.8,158.7,156.1,155.7,:
5,Estonia,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
6,Ireland,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
7,Greece,:,:,:,:,:,:,:,:,:,...,134.1,134.1,133.6,134,131.8,129,128.7,126.4,125,:
8,Spain,81.4,81.6,81.9,82,82.6,83.2,82.3,81.9,80.9,...,160.3,161.9,163.8,173.1,172.3,172.8,170.4,165.4,164.2,:
9,France,:,:,:,:,:,:,:,:,:,...,141.9,144.3,145.6,162.6,164.1,164.7,162.9,160,158.7,:
10,Croatia,:,:,:,:,:,:,:,:,:,...,123.4,123.8,123.7,123.7,123.8,123.5,124,123.8,123.1,121.9
11,Italy,:,:,:,:,:,:,:,:,:,...,162.5,164.5,165.3,164.3,161.8,160.6,156.9,151.3,145.2,:
12,Cyprus,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
13,Latvia,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
14,Lithuania,:,:,:,:,:,:,:,:,:,...,182.4,170,168,179,177.8,181.6,188.5,188.3,182.7,:
15,Luxembourg,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
16,Hungary,:,:,:,:,:,:,:,:,:,...,279.8,287.8,291.9,309.2,298.5,290.4,271.6,263.6,246.8,:
17,Malta,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
18,Netherlands,:,:,:,:,:,:,:,:,:,...,166.1,167.4,167,194,194.8,194.2,193.7,194.5,194,:
19,Austria,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
20,Poland,:,:,:,:,:,:,:,:,:,...,192.4,194.4,195.9,194.7,190.7,186.2,177.9,173.3,171.4,:
21,Portugal,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,145.3,:
22,Romania,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
23,Slovenia,:,:,:,:,:,:,:,:,:,...,137.4,148.9,145.2,140,145,144.3,143.8,144.9,144.2,:
24,Slovakia,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
25,Finland,:,:,:,:,:,:,:,:,:,...,135.5,139.1,142.8,143.4,144.5,145.5,144.7,142.2,141.4,:
26,Sweden,74.1,74.8,74.8,76,76.2,76.2,76.2,75.8,75.7,...,156.8,158.2,161,166.1,168.3,169.4,163.9,158.9,159,:
27,Norway,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
28,Switzerland,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
29,United Kingdom,76.5,76.7,76.3,76.7,76.7,77,77.2,77.2,77.1,...,:,:,:,:,:,:,:,:,:,:
30,Montenegro,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
31,North Macedonia,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
32,Albania,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
33,Serbia,:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
34,Türkiye,:,:,:,:,:,:,:,:,:,...,751.3,771.6,777.9,799.2,816.7,817,820.3,842.5,871.1,:

In [10]:
filt = df['Country'] == 'Germany'
df_germany = df_new.loc[filt]
df_germany

,Country,1996-01,1996-02,1996-03,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,...,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07
4,Germany,87.3,87.4,87.7,87.8,88.8,89.4,89.7,89.8,89.2,...,154,159,158.4,160.1,162.1,161.8,158.7,156.1,155.7,:

In [ ]:
x = df_germany.set_index('Country')
x

In [16]:
df_germany.to_csv('output_price_grain_starch_germany.csv', index = False)

In [16]:
#wetterdaten = pd.read_csv('https://raw.githubusercontent.com/TechLabs-Dortmund/Food-price-forecast/main/Datasets/food_price_and_air_temperature.csv?token=GHSAT0AAAAAACF5MZDWT6WW4TDD22FMTBB2ZGNK7EQ')
#downloaden 
#wetterdaten.to_csv("food_price_and_air_temperature.csv", index = False)
# wieder laden um zu sehen, ob es makellos funktioniert hat 
df_w = pd.read_csv("C:/Users/tom/Food Price Forecasting/food_price_and_air_temperature.csv")
df_w

     Unnamed: 0     Date  Food_Price  Air_Temperature
0             0  1996-01        74.9            -2.82
1             1  1996-02        75.5            -2.18
2             2  1996-03        76.1             1.00
3             3  1996-04        76.4             8.40
4             4  1996-05        76.2            11.15
..          ...      ...         ...              ...
326         326  2023-03       147.6             5.74
327         327  2023-04       146.5             7.53
328         328  2023-05       146.2            13.08
329         329  2023-06       146.0            18.56
330         330  2023-07         NaN            18.72

[331 rows x 4 columns]

In [15]:
df_germany_g_s = df_germany.transpose()
x = df_germany_g_s[4].tolist()
x_neu = x[1:]
x_neu

['Germany',
 87.3,
 87.4,
 87.7,
 87.8,
 88.8,
 89.4,
 89.7,
 89.8,
 89.2,
 88.5,
 88.4,
 88.1,
 87.7,
 87.3,
 87,
 86.6,
 86.4,
 85.8,
 85.5,
 84.9,
 84.5,
 83.7,
 83.6,
 83.5,
 83.6,
 83,
 83,
 82.6,
 82.4,
 81.8,
 81.7,
 81.5,
 81.2,
 80.8,
 80.7,
 80.7,
 80.2,
 80,
 79.8,
 79.7,
 79.5,
 79.4,
 79.1,
 78.9,
 78.6,
 78.5,
 78.6,
 78.8,
 79,
 79.1,
 79.3,
 79.2,
 79.1,
 79.6,
 79.6,
 81.5,
 81.9,
 82.4,
 82.7,
 82.9,
 83.4,
 83.4,
 83.3,
 83.3,
 83.3,
 83.4,
 83.6,
 83.5,
 83.6,
 83.6,
 83.5,
 83.4,
 83.6,
 83.5,
 83.3,
 83.4,
 83.3,
 83,
 82.7,
 82.2,
 84.1,
 85,
 85.9,
 86,
 86,
 85.8,
 85.7,
 85.6,
 85.5,
 85.8,
 85.6,
 85.5,
 86.5,
 87,
 87.4,
 88,
 88.5,
 88.5,
 88.3,
 88.4,
 88.4,
 88,
 87.5,
 87.3,
 86.9,
 85,
 84.2,
 84,
 83.5,
 83.1,
 82.6,
 82.9,
 82.6,
 83,
 82.6,
 82.6,
 82.4,
 82.4,
 82.8,
 82.8,
 82.8,
 82.9,
 83.5,
 83.5,
 83.5,
 83.4,
 83.5,
 83.7,
 85.7,
 87.5,
 88.3,
 89.2,
 90.5,
 92.1,
 92.1,
 93.2,
 93.5,
 93.6,
 95.4,
 99.8,
 105,
 107.4,
 109.6,
 110.4,
 112.7,
 112.8,
 113.6,
 114.1,
 113.3,
 111.9,
 109.7,
 109.3,
 105.5,
 102.5,
 101.2,
 99.4,
 97.1,
 95.9,
 94.6,
 93.6,
 92.8,
 92.7,
 92,
 91,
 89,
 88.2,
 86.8,
 87.2,
 85,
 85,
 85,
 84.5,
 84.7,
 85.1,
 87.3,
 91.3,
 96.6,
 101.6,
 102.3,
 102.5,
 108.6,
 109.2,
 109.3,
 110.1,
 111.1,
 111.4,
 110.5,
 110.4,
 110.5,
 111.2,
 109.8,
 108.8,
 108.5,
 108.4,
 107.5,
 107.4,
 108.2,
 108.3,
 109.2,
 110.2,
 112.1,
 113.7,
 115.2,
 115.4,
 116.5,
 116.2,
 115.5,
 115.1,
 115.5,
 114.8,
 113,
 111.9,
 110.6,
 109.3,
 107.4,
 107.2,
 106,
 105.7,
 106.2,
 105.6,
 105.3,
 105,
 104.4,
 103.7,
 102,
 101.5,
 101.3,
 101.5,
 101,
 100.6,
 100.8,
 100.6,
 100.4,
 100.2,
 99.8,
 99.6,
 99.4,
 99.3,
 99.2,
 99.1,
 99.2,
 98.7,
 98.4,
 98.3,
 98.1,
 98,
 97.9,
 97.7,
 97.4,
 96.2,
 96.2,
 96.4,
 96.7,
 96.9,
 97,
 97,
 97.4,
 97.8,
 97.9,
 98.3,
 98.2,
 98.8,
 98.8,
 99,
 98.2,
 98.2,
 98.2,
 98.4,
 99,
 98.9,
 99.5,
 100.5,
 101.9,
 102.4,
 102.6,
 102.8,
 104.2,
 104.5,
 104.5,
 104,
 104.1,
 103.7,
 103.5,
 103.1,
 102,
 101.9,
 101.3,
 101.3,
 101.2,
 101.3,
 101.3,
 101.6,
 101.4,
 101.3,
 100.9,
 100.5,
 100.7,
 100.9,
 101.2,
 101.1,
 102,
 102.4,
 102.7,
 104.6,
 105.3,
 105.9,
 106.5,
 107.2,
 108.2,
 112.8,
 115.2,
 117.1,
 120.7,
 121.7,
 130.6,
 137,
 140.8,
 142,
 143.7,
 144.8,
 146.6,
 154,
 159,
 158.4,
 160.1,
 162.1,
 161.8,
 158.7,
 156.1,
 155.7,
 ':']

In [21]:
df_w['grain_starch_output_price'] = x_neu
df_w
df_w.to_csv("food_price_air_temperature_grain_starch_output_price.csv", index = False)